profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('<str:ref_code>/', views.index, name='index')
]

referral_link/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls', namespace='profiles'))    
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from . import utils

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    code = models.CharField(max_length=12, blank=True)
    recommended_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='ref_by')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.code}'

    def get_recommended_profiles(self):
        profiles = Profile.objects.all()
        my_recs = [profile for profile in profiles if profile.recommended_by == self.user]
        return my_recs

    def save(self, *args, **kwargs):
        if self.code == '':
            code = utils.generate_ref_code()
            self.code = code
        super().save(*args, **kwargs)

profiles/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User


def index(request, *args, **kwargs):
    code = str(kwargs.get('ref_code'))
    try:
        profile = Profile.objects.get(code=code)
        request.session['ref_profile'] = profile.id
    except:
        pass
    context = {}
    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        my_recs = profile.get_recommended_profiles()
        context = {
            'my_recs': my_recs
        } 
    return render(request, 'profiles/index.html', context)


def signup(request):
    profile_id = request.session.get('ref_profile')
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        if profile_id is not None:
            recommended_by_profile = Profile.objects.get(id=profile_id)
            instance = form.save()
            registered_user = User.objects.get(id=instance.id)
            registered_profile = Profile.objects.get(user=registered_user)
            registered_profile.recommended_by = recommended_by_profile.user
            registered_profile.save()
        else:
            form.save()

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('profiles:index')
    context = {
        'form': form,
    }
    return render(request, 'profiles/signup.html', context)

profiles/templates/profiles/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    home
{% endblock title %}
    

{% block content %}
    
    {% if request.user.is_authenticated %}
        {{request.user}}
        {% if my_recs %}
            <h1>My Recommendations</h1>
            <ul>
            
            {% for my_rec in my_recs %}
                <li>{{ my_rec.user }}</li>
            {% endfor %}
                
            </ul>
        {% else %}
            <h1>You didn't recommend anyone yet</h1>
    {% endif %}
    {% else %}
        <a href="{% url 'profiles:signup' %}">
            <button class="btn btn-primary">Create an account</button>
        </a>
    {% endif %}
        
{% endblock content %}
    

profiles/templates/profiles/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Sign Up
{% endblock title %}
    

{% block content %}
    <form action="" method='POST'>
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Signup</button>
    </form>
{% endblock content %}
    

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Ref link proj | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
        
        {% block content %}
            
        {% endblock content %}
            
    </div>

    <!-- bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  
  </body>
</html>